language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -qq flake8"
  - "pip install coveralls --quiet"
  - "pip install ."

# command to run tests
script:
  - nosetests -s -v --with-coverage --cover-package=constraint
  - flake8 --ignore E501 constraint examples tests

after_success:
  - coveralls
