// Generated by CoffeeScript 1.12.5
(function() {
  var PDFDocument, doc, fs;

  PDFDocument = require('pdfkit');

  fs = require('fs');

  doc = new PDFDocument;

  doc.pipe(fs.createWriteStream('out.pdf'));

  doc.end();

}).call(this);
