name: typesetting CI

on: [push, pull_request]

jobs:
  run:
    name: "Build using Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["7.1", "7.2", "7.3", "7.4", "7.5", "7.6", "7.7", "7.8", "7.9", "8.0", "8.1", "8.2", "8.3", "current"]
        racket-variant: ["BC", "CS"]
        # CS builds are only provided for versions 7.4 and up so avoid
        # running the job for prior versions.
        exclude:
          - {racket-version: "7.1",    racket-variant: "CS"}
          - {racket-version: "7.2",    racket-variant: "CS"}
          - {racket-version: "7.3",    racket-variant: "CS"}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: Bogdanp/setup-racket@v0.11
      with:
        distribution: 'full'
        version: ${{ matrix.racket-version }}
        variant: ${{ matrix.racket-variant }}

    - name: install xenomorph
      run: raco pkg install --deps search-auto https://github.com/mbutterick/typesetting.git?path=xenomorph#main

    - name: install hyphenate
      run: raco pkg install --deps search-auto https://github.com/mbutterick/typesetting.git?path=hyphenate#main

    - name: install fontland
      run: raco pkg install --deps search-auto https://github.com/mbutterick/typesetting.git?path=fontland#main

    - name: install pitfall
      run: raco pkg install --deps search-auto https://github.com/mbutterick/typesetting.git?path=pitfall#main

    - name: install quad
      run: raco pkg install --deps search-auto https://github.com/mbutterick/typesetting.git?path=quad#main

    - name: Run hyphenate tests
      run: xvfb-run raco test -j 4 -p hyphenate

    - name: Run xenomorph tests
      run: xvfb-run raco test -j 4 -p xenomorph
      
    - name: Run fontland tests
      run: xvfb-run raco test -j 4 -p fontland

    - name: Run pitfall tests
      run: xvfb-run raco test -j 4 -p pitfall

    - name: Run the ptests
      run: xvfb-run racket -l ptest/all

    - name: Run quad tests
      run: xvfb-run raco test -j 4 -p quad

    - name: Run the qtests
      run: xvfb-run racket -l qtest/all
